import path from "path";
import express from "express";
import dotenv from "dotenv";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";

dotenv.config();

const PORT = 3000;
const apiKey = process.env.GEMINI_API_KEY || "";
const ai = apiKey ? new GoogleGenAI({ apiKey }) : null;

function extractJsonObject(text: string) {
  const match = text.match(/\{[\s\S]*\}/);
  if (!match) return null;
  try {
    return JSON.parse(match[0]);
  } catch {
    return null;
  }
}

async function generateAIResponse(prompt: string) {
  if (!ai) return null;
  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
    });
    return response.text?.trim() ?? null;
  } catch (error) {
    console.error("AI generation failed:", error);
    return null;
  }
}

const defaultAnalysis = {
  calories: 120,
  foodName: "Unknown Meal",
  predictiveRisk: "low",
  summary: "A standard meal analysis placeholder generated by AuraNutrics.",
  macronutrients: {
    protein: 12,
    carbs: 28,
    fat: 8,
  },
  healthInsights: "Baseline analysis available; connect GEMINI_API_KEY for richer, live insights.",
  nutrients: {
    protein: "12g",
    carbs: "28g",
    fat: "8g",
  },
};

const defaultAdvice =
  "I am currently operating in fallback mode. Please provide more details or configure the GEMINI_API_KEY for real-time AI advice.";

async function startServer() {
  const app = express();
  app.use(express.json());

  app.get("/api/health", (_req, res) => {
    res.json({ status: "ok", timestamp: new Date().toISOString() });
  });

  app.post("/api/vision/analyze", async (req, res) => {
    const { base64Image } = req.body;
    if (!base64Image) {
      return res.status(400).json({ error: "base64Image is required" });
    }

    const prompt = `Analyze the following base64-encoded food image and return a JSON object with keys: foodName, calories, predictiveRisk, summary, nutrients. Image data: ${base64Image}`;
    const aiText = await generateAIResponse(prompt);
    const result = aiText ? extractJsonObject(aiText) : null;

    res.json(result || defaultAnalysis);
  });

  app.post("/api/health/advice", async (req, res) => {
    const { history, profile, biometrics, userMessage } = req.body;
    if (!userMessage) {
      return res.status(400).json({ error: "userMessage is required" });
    }

    const prompt = `You are Aura AI, a precision health intelligence assistant. Use the following profile, nutrition history, and biometrics to deliver a concise, actionable health insight in plain text. Profile: ${JSON.stringify(profile)} History: ${JSON.stringify(history)} Biometrics: ${JSON.stringify(biometrics)} User question: ${userMessage}`;
    const aiText = await generateAIResponse(prompt);

    res.json({ advice: aiText || defaultAdvice });
  });

  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`AuraNutrics Server running on http://localhost:${PORT}`);
  });
}

startServer();
